config/routes.rb
Ghfood::Application.routes.draw do 
  root :to => "application#index"
  match "/recipe/1" => "application#bolo", as: "bolo"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index 
  end
  def bolo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/bolo.html.haml
#logo.span4.offset1
  =image_tag "/img/onafaim-logo-256.png"
#photo.span6
  =image_tag "/img/bolo.jpg", :class => "img-polaroid"

%h1.span3.offset1 Spaghettis à la bolognaise

#ingredients.span3.offset1
  %p Pour 120 personnes :
  %ul
    %li=link_to "30kg de spaghettis"
    %li=link_to "10kg de viande haché"
    %li=link_to "10kg de sauce tomate"
    %li=link_to "1l d'huile de palme"
    %li=link_to "1 carotte"
#nutritional.span2
  %p Valeurs nutritionnelles :
  %ul
    %li Nombre de calories : 576 kcal/prs
    %li Prix : 126.20€
    %li Temps : 8h

.woot{:style => "position:absolute;left:180px;top:500px;"}
  %span.label Jeune
  %span.label.label-success Sans Porc
  %span.label.label-warning Pas cher
  %span.label.label-important Rapide
  %span.label.label-info Viande
  %span.label.label-inverse Simple

      
.row
  #actions
    .span3.offset5
      %button.btn.btn-primary.btn-large#go
        EN CUISINE !
        %br
        %span.caret

%hr 
#tl

%ul#steps
  %li.li-height
    .circle
    %h3
      Faites cuire la carotte !
      %hr
    %br
    %iframe{:width => "420", :height => "315", "src" => "http://www.youtube.com/embed/_uBafUuSX9M", "frameborder" => "0", "allowfullscreen" => "true"}
    =image_tag "/img/carotte.jpg", :class => "img-polaroid img-rounded"
    %button.btn.btn-primary
      Étape suivante
      %span.caret
  - ['Faites rôtir la viande hachée','Ajoutez la sauce tomate',"Versez l'huile et laissez migoter","Faire bouillir de l'eau","Mettez les pâtes dans l'eau bouillante"].each do |inst|
    %li.li-height 
      .circle
      %h3
        = inst
        %hr
      %button.btn.btn-primary
        Étape suivante
        %span.caret



=link_to (image_tag "/img/up.png", :width => "50px"), "#" , :class => "up-left"

%a#iphone.btn.btn-large.btn-block.btn-success.big-button.span3.offset4{:href=>"#"}
  .pwet
    %i.icon-search.icon-white.icon-camera{:height => "40px", :width => "40px"}
    Prendre une photo du plat et la partager !

=link_to (image_tag "/img/up.png", :width => "50px"), "#" , :class => "up-right"

.span2.offset5
  .div{:style => "float:left;"}
    =link_to (image_tag "/img/f_logo.png", :width => "75px"), "#" , :class => "up-right"
  .div{:style => "float:right;"}
    =link_to (image_tag "/img/twitter.png", :width => "75px"), "#" , :class => "up-right"

app/views/application/index.html.haml
.offset3
  %img.margin-down.img-rounded{:src => "/img/main_icon.png"}

.offset4.input-append
  %input#appendedInputButton{:type => "text", :placeholder => "Cherchez une recette!", :width => "500px"}
  %button.btn.input-append{:type => "button"}
    %i.icon-search

.margin-down

%ul.thumbnails
  %li.span4
    .thumbnail
      = link_to (image_tag "/img/bolo.jpg"), bolo_path
    .caption
      %h3 Spaghettis à la bolognaise
      %p Une recette classique mais délicieuse, rapide et peu onéreuse idéale pour toutes les faims.
  %li.span4
    .thumbnail 
      = link_to (image_tag "/img/carbo.jpg"), bolo_path
    .caption 
      %h3 Spaghettis à la carbonara
      %p Des pâtes, des pâtes, oui mais des panzannis !
  %li.span4
    .thumbnail 
      = link_to (image_tag "/img/1.jpg"), bolo_path
    .caption
      %h3 Spaghettis à la bolognaise
      %p Des pâtes, du fromage, des champignons, un plein de douceur pour votre palais.
%ul.thumbnails
  %li.span4
    .thumbnail 
      = link_to (image_tag "/img/2.jpg"), bolo_path
    .caption
      %h3 Spaghettis à la bolognaise
      %p Des pâtes, du fromage, des champignons, un plein de douceur pour votre palais.
  %li.span4
    .thumbnail 
      = link_to (image_tag "/img/3.jpg"), bolo_path
    .caption
      %h3 Spaghettis à la bolognaise
      %p Des pâtes, du fromage, des champignons, un plein de douceur pour votre palais.
  %li.span4
    .thumbnail 
      = link_to (image_tag "/img/4.jpg"), bolo_path
    .caption
      %h3 Spaghettis à la bolognaise
      %p Des pâtes, du fromage, des champignons, un plein de douceur pour votre palais.

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "On A Faim!"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .container
      .content
        .main-content
          = bootstrap_flash
          = yield
    
      %footer
        -# %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"